### ISSUE TITLE
Problem with scrapy dependency

### ISSUE THREAD

**Issue by RobinClowers** [nimia/public_drown_scanner#12]
I just tried to get this running on Ubuntu and can't seem to get it working. The readme says to `apt-get install scrapy`, but there is no package called that, it's `python-scrapy`. I installed that package, but I still get an import error:

```
$ python scanner.py localhost 80
Traceback (most recent call last):
  File "scanner.py", line 18, in <module>
    from scapy_ssl_tls.ssl_tls import *
ImportError: No module named scapy_ssl_tls.ssl_tls
```

**Comment by djengineerllc** [comment]
https://github.com/nimia/public_drown_scanner/issues/10
These ppl said that they used pip to install that module:
scapy-ssl_tls

sudo pip install scapy-ssl_tls

Not sure if that works or not, but maybe ?

**Comment by WhyteFyre** [comment]
Just installed scapy-ssl_tls via pip under root. scanner.py now runs as intended.

**Comment by jankal** [comment]
Me too. Works.

**Comment by nimia** [comment]
Yes, my bad. Added this to the readme now. Thanks!
