### ISSUE TITLE
cant get it to run..

### ISSUE THREAD

**Issue by dirtbag** [nimia/public_drown_scanner#15]
[jason@linux ~]$ ./drown_scanner.py localhost 443
Traceback (most recent call last):
  File "./drown_scanner.py", line 21, in <module>
    from pyx509.pkcs7.asn1_models.X509_certificate import Certificate
ImportError: No module named pyx509.pkcs7.asn1_models.X509_certificate
[jason@linux ~]$ 

[jason@linux ~]$ pip search asn1
zozol                     - Broken ASN1 for DSTU
rfc3161                   - Python implementation of the RFC3161 specification, using pyasn1
pyasn1-modules            - A collection of ASN.1-based protocols modules.
  INSTALLED: 0.0.8 (latest)
asn1ate                   - ASN.1 translation library.
pyasn1                    - ASN.1 types and codecs
  INSTALLED: 0.1.9 (latest)
asn1crypto                - Fast ASN.1 parser and serializer with definitions for private keys, public keys, certificates, CRL, OCSP, CMS, PKCS#7,
                            PKCS#8, PKCS#12, PKCS#5, X.509 and TSP

**Comment by nimia** [comment]
Thanks for reaching out.
I've included instructions for obtaining the dependencies in the README.md file.
Please try again, and reopen the issue if the problem persists.
thanks,
Nimrod
