### ISSUE TITLE
Dependencies on CentOS7

### ISSUE THREAD

**Issue by bobmclaren** [nimia/public_drown_scanner#17]
I just went through dependency hell on 4 different servers before I finally got this script to run on my CentOS 7 server.

In the hopes of saving someone else the torment I endured, here is a quick rundown of what I had to do.  Bear in mind that this was on a pretty stripped down installation of CentOS, so a lot of things people take for granted (like gcc) were not installed.

(logged in as root)

```
yum install gcc gcc-c++ python-devel libpcap-devel
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
pip install enum pcapy pyasn1 pycrypto scapy scapy-ssl-tls
```

After all this, I still receive the following warning message, but the script appears to be running as expected.

> Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality
> ImportError('cannot import name TLSHandshake',)

**Comment by nimia** [comment]
Much appreciated!
I feel this is somewhat of a rare case, so the readme simply links to this issue.
Thanks a lot for taking the time to document this!

**Comment by Slammis** [comment]
Thanks!

However it didnt help me on my Centos7 box.

I get the following error
[root@cacti ~]# python scanner.py localhost 443 -bare
  File "scanner.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Iam new to python so any idea would be nice :-)

**Comment by biergaizi** [comment]
@Slammis

You downloaded the GitHub webpage instead of the source file, the solution should be easy :laughing:

**Comment by bobmclaren** [comment]
@Slammis That looks to me like your scanner.py contains unexpected HTML content rather than the script content. Something has likely gone awry with your download.

**Comment by JZiemba** [comment]
python-pyasn1 has been installed (CentOS 6.7) however also receiving "ImportError: No module named asn1" error.
