### ISSUE TITLE
missing tcpdump dependency

### ISSUE THREAD

**Issue by beyerservice** [nimia/public_drown_scanner#18]
`WARNING: Failed to execute tcpdump. Check it is installed and in the PATH`
working ok I think without it.
but:
`WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Traceback (most recent call last):
  File "scanner.py", line 18, in <module>
    from scapy_ssl_tls.ssl_tls import *
ImportError: No module named scapy_ssl_tls.ssl_tls
`
last line was because I forgot 

> pip install scapy-ssl_tls
>  :-)

**Comment by sarah-github** [comment]
tcpdump works when executing the script as root.

**Comment by Matt3o12** [comment]
`tcpdump` is not always installed, though, and it is not listed as a requirement.
