### ISSUE TITLE
Missing 'enum' directory

### ISSUE THREAD

**Issue by blha303** [nimia/public_drown_scanner#2]
https://github.com/nimia/public_drown_scanner/blob/master/scanner.py#L2 says `sys.path.append("./enum/enum")` but there is no enum directory. Related to #1. As an aside, this would be alternative code that doesn't have `enum` as a required import:

```
class Protocol:
    BARE_SSLv2 = 1
    ESMTP      = 2
    IMAP       = 3
    POP3       = 4
```

This behaves more or less the same as an enum, although the values aren't immutable.

Also there's zero instructions for how to actually run this, what's needed etc, but I'll wait for the requirements.txt PR to be completed.

**Comment by martinseener** [comment]
In OSX 10.11.3 the error reads like this:
`Traceback (most recent call last):
  File "scanner.py", line 3, in <module>
    from enum import Enum
ImportError: No module named enum`

You (@thekeez @blha303) can "fix" this by using python3 (`brew install python3`) but you'll the run into another problem:

`File "scanner.py", line 148
    except ValueError, e:
                     ^
SyntaxError: invalid syntax`

Okay, i was able to get it running. Check my comment on the Pull Request: https://github.com/nimia/public_drown_scanner/pulls#issuecomment-190753172

**Comment by akninety** [comment]
@blha303 @martinseener I'm running in to the same issue.  Platform is Windows 7.

**Comment by nimia** [comment]
Hi, thanks for helping me make this tool more accessible, I'm grateful for your feedback.
I've just updated the README.md with instructions which I hope cover all dependencies.
Are there still missing dependencies?

**Comment by blha303** [comment]
I have a service running that I wanted to check for SSLv2, here's the output

```
$ python scanner.py localhost 45000
Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality
ImportError('cannot import name TLSHandshake',)
Testing localhost on port 65000
localhost: Case 3b; Connection reset by peer when waiting for server hello
localhost: Server is NOT vulnerable with cipher RC2_128_CBC_EXPORT40_WITH_MD5, Message: 3b: no tls

localhost: Case 3b; Connection reset by peer when waiting for server hello
localhost: Server is NOT vulnerable with cipher RC4_128_EXPORT40_WITH_MD5, Message: 3b: no tls

localhost: Case 3b; Connection reset by peer when waiting for server hello
localhost: Server is NOT vulnerable with cipher RC4_128_WITH_MD5, Message: 3b: no tls

localhost: Case 3b; Connection reset by peer when waiting for server hello
localhost: Server is NOT vulnerable with cipher DES_64_CBC_WITH_MD5, Message: 3b: no tls

```

I believe this was discussed in the requirements.txt PR

**Comment by nimia** [comment]
OK. I'm aware of the ImportError problem and will try to address it.
Closing this issue for now. Please let me know if there are still warranted additions to the dependencies list.
