### ISSUE TITLE
a prebuilt docker image on dockerhub would be nice

### ISSUE THREAD

**Issue by bbigras** [nimia/public_drown_scanner#32]
You can set up an automated build on docker hub to have a new Docker image built every time this repo changes.

Pulling the image would be a tiny bit faster than building it.

**Comment by nimia** [comment]
Dear Bruno,

I'm afraid I am unfamiliar with docker, and very pressed for time with support for everything DROWN-related. If you could find the time to create such an image and send a PR, I'd be happy to use it, provided it has been tested against vulnerable servers as well.

best,
Nimrod
