### ISSUE TITLE
ImportError: No module named ssl_tls

### ISSUE THREAD

**Issue by B-RxA** [nimia/public_drown_scanner#33]
I get the following error after installing all the requirements:

python scanner.py www.test.com 443
Traceback (most recent call last):
  File "scanner.py", line 25, in <module>
    from ssl_tls import *
ImportError: No module named ssl_tls

I have the package installed via pip: /usr/lib/python2.6/site-packages/scapy_ssl_tls/

Any ideas?

**Comment by kaptajnen** [comment]
You need to modules included in this repo, not the version you get from pip. I.e. make sure you have the "pyx509" and "scapy-ssl_tls" folders from https://github.com/nimia/public_drown_scanner

**Comment by nimia** [comment]
Indeed. Thank you Jonas for helping other users, much appreciated.
