### ISSUE TITLE
unsexy error 

### ISSUE THREAD

**Issue by suedi** [nimia/public_drown_scanner#34]
``` python
> python scanner.py localhost 443
  File "scanner.py", line 156
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

I am on Arch linux and tried to mangle through the dependency lists that you supplied 
for other distros.

Get no import error but get the, for me, rather strange error.

Both python3.4 and python2 is installed but
/usr/bin/python is symlinked to python3.4

I just cloned git and have not edited?

**Comment by nimia** [comment]
Thanks for your report.
The script is written for python2. I've changed the shebang line accordingly, should work now.

best,
Nimrod
