### ISSUE TITLE
File "scanner.py", line 156 -- SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by drankinatty** [nimia/public_drown_scanner#36]
This is running on Archlinux, I have run into the following syntax issue:

```
$ python scanner.py localhost 443
  File "scanner.py", line 156
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

Admittedly, this may be user error, but the example usage given makes that a long shot. Why is it looking for `e:` on Linux?

**Comment by cnelsonsic** [comment]
Try running it with Python 2.
