### ISSUE TITLE
Gives wrong answer for SMTP servers that use paused greeting

### ISSUE THREAD

**Issue by paulehoffman** [nimia/public_drown_scanner#39]
pechora1.icann.org uses Sendmail's "greet_pause" feature to delay sending the initial SMTP greeting by 20 seconds. This causes the scanner to emit "Case 3b; Connection reset by peer when waiting for server hello". However, even when I change the scanner code to:
   SOCKET_TIMEOUT = 30
the same message is given. It seems that the socket logic isn't fully compensating for long-delayed SMTP banners.

**Comment by nimia** [comment]
Thanks for reporting the issue.
I haven't been able to successfully connect with STARTTLS to this host. Changing the timeout indeed does not work, and results in getting RSTs from the host. Could you please attack a packet capture of a successful STARTTLS handshake with this host using another client? I can probably change the code accordingly once I have that. Just reply here, I'll re-open the issue.

thanks again,
Nimrod
