### ISSUE TITLE
ImportError: No module named pyx509.pkcs7.asn1_models.X509_certificate

### ISSUE THREAD

**Issue by jrmain** [nimia/public_drown_scanner#46]
Can't seem to get around this error. Installed all dependencies as indicated in the readme. Any suggestions?

**Comment by nimia** [comment]
Do you have the pyx509 directory alongside the scanner.py file?

**Comment by jrmain** [comment]
I do now. Problem solved. Now I get this:

```
Traceback (most recent call last):
  File "scanner.py", line 25, in <module>
    from pyx509.pkcs7.asn1_models.X509_certificate import Certificate
  File "/home/jrivett/drown-scanner/pyx509/pkcs7/asn1_models/X509_certificate.py", line 32, in <module>
    from tools import *
  File "/home/jrivett/drown-scanner/pyx509/pkcs7/asn1_models/tools.py", line 24, in <module>
    from decoder_workarounds import decode
  File "/home/jrivett/drown-scanner/pyx509/pkcs7/asn1_models/decoder_workarounds.py", line 10, in <module>
    class BooleanFixDerDecoder(derDecoder.Decoder): pass
AttributeError: 'module' object has no attribute 'Decoder'

```

**Comment by nimia** [comment]
Have you tried this:
https://github.com/nimia/public_drown_scanner/issues/30
?

**Comment by jrmain** [comment]
I'm on Ubuntu 12.04, not CentOS. And the error in that report doesn't seem related to what I'm seeing. But I could easily be wrong about that.

**Comment by nimia** [comment]
Fair enough. This looks like an issue with the pyasn1 package.
These lines should work on a python shell:

```
from pyasn1.codec.der import decoder as derDecoder
import inspect
inspect.getsourcefile(derDecoder.Decoder)
```

and should print something similar to

/usr/lib/python2.7/dist-packages/pyasn1/codec/cer/decoder.py

What version of pyasn1 do you have running?

**Comment by jrmain** [comment]
The first two commands just return the Python prompt. The third command results in this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Decoder'
```

**Comment by nimia** [comment]
Oh, makes sense.
Please try:
inspect.getsourcefile(derDecoder)
Also, what version of pyasn1 do you have running?

**Comment by jrmain** [comment]
inspect.getsourcefile(derDecoder) gives me this:
`'/usr/lib/python2.7/dist-packages/pyasn1/codec/der/decoder.py'`

pyasn1 (0.0.11a0)

**Comment by nimia** [comment]
Sorry for the late response.
Would it be possible for you to try pyasn1 version 0.1.9?

**Comment by jrmain** [comment]
Forgive the dumb question, but how do I upgrade pyasn1?

**Comment by nimia** [comment]
On the contrary, I'm unsure myself.
I'd try moving the `/usr/lib/python2.7/dist-packages/pyasn1/` directory somewhere else,
and installing 0.1.9 according to these instructions:
https://pypi.python.org/pypi/pyasn1

**Comment by jrmain** [comment]
That seems to have done the trick. The scanner now runs as expected, reporting the results of a series of tests, like this:

```
Testing localhost on port 443
localhost: Case 3d; Server hello did not contain SSLv2
localhost: Server is NOT vulnerable with cipher RC2_128_CBC_EXPORT40_WITH_MD5, Message: 3d: no tls
localhost: Case 3d; Server hello did not contain SSLv2
localhost: Server is NOT vulnerable with cipher RC4_128_EXPORT40_WITH_MD5, Message: 3d: no tls
localhost: Case 3d; Server hello did not contain SSLv2
localhost: Server is NOT vulnerable with cipher RC4_128_WITH_MD5, Message: 3d: no tls
localhost: Case 3d; Server hello did not contain SSLv2
localhost: Server is NOT vulnerable with cipher DES_64_CBC_WITH_MD5, Message: 3d: no tls        
```

**Comment by basvanbeeknl** [comment]
For me this fixed it:

yum install python-pyasn1
