### ISSUE TITLE
 python-enum : Conflicts: python-enum34 but 1.1.2-1 is to be installed.

### ISSUE THREAD

**Issue by rubo77** [nimia/public_drown_scanner#47]
On Debian stretch I cannot install the requirements, aptitude doesn't suggest any solution for this problem.

how can I resolve this?

**Comment by rubo77** [comment]
It seems the package is not needed in Debian stretch any more (see #49)

**Comment by tintinweb** [comment]
can be avoided by completely getting rid of the `enum` and just use ordinary class attributes for this

```
- from enum import Enum
...
- class Protocol(Enum):
+ class Protocol(object):
```

**Comment by nimia** [comment]
Thanks!
