### ISSUE TITLE
ValueError when used with docker

### ISSUE THREAD

**Issue by The-Judge** [nimia/public_drown_scanner#52]
Hi there,

I build the docker container as you described.
Afterwards, I try to run a scan like this:

`docker run -it --rm public-drown-scanner scanner.py 37.120.171.78 443`

This is what I get:

Traceback (most recent call last):
  File "scanner.py", line 359, in <module>
    port = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '37.120.171.78'

The result is the same, if I use DNS names instead of the IP.

**Comment by nimia** [comment]
I'm unfamiliar with Docker, but it looks like there's an extra argument somewhere, and the IP is erroneously parsed as a port. Perhaps try removing the `scanner.py` argument to Docker:

`docker run -it --rm public-drown-scanner 37.120.171.78 443`

**Comment by lavraalex** [comment]
???
How

**Comment by nimia** [comment]
I'm closing this for now, please let me know if the solution doesn't work.
best,
Nimrod
