### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by stevenlee87** [nimia/public_drown_scanner#56]
centos5.4
python enviroment 2.7.9 

python public_drown_scanner-master/scanner.py 10.10.10.2 443
Traceback (most recent call last):
  File "public_drown_scanner-master/scanner.py", line 22, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/site-packages/scapy/all.py", line 11, in <module>
    from scapy.config import *
  File "/usr/local/lib/python2.7/site-packages/scapy/config.py", line 388
    "sctp", "vrrp", "ipsec", "lltd", "vxlan", "ssl_tls" ]    contribs = dict()
                                                                    ^
SyntaxError: invalid syntax

**Comment by nimia** [comment]
Can you run
`from scapy.all import *`
in unrelated code, or just from the python shell?
If the above line doesn't work, then the problem is with your scapy installation, not with the scanner itself.

**Comment by stevenlee87** [comment]
pip install scapy==2.3.1 -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com is good.
if pip install scapy will install scapy-2.3.3,then report err:SyntaxError: invalid syntax
