### ISSUE TITLE
Kali Linux ImportError cannot import name TLSHandshake

### ISSUE THREAD

**Issue by djengineerllc** [nimia/public_drown_scanner#9]
Hi I've been trying to set this up on Kali linux which I believe is debian based.  It already has python-enum34, but I tried with either library and it was still the same.

Also, scapy install was apt-get install python-scapy.  I did install python-crypto.

Ok, so I ran the script and go the error: "**Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality**" and "**ImportError('cannot import name TLSHandshake')**"

Then it continues on with check information.

Testing server on port 443
server: Case 3b; Connection reset by peer when waiting for server hello
server: Server is NOT vulnerable with cipher RC2_128_CBC_EXPORT40_WITH_MD5, Message: 3b: no tls

server: Case 3b; Connection reset by peer when waiting for server hello
server: Server is NOT vulnerable with cipher RC4_128_CBC_EXPORT40_WITH_MD5, Message: 3b: no tls

server: Case 3b; Connection reset by peer when waiting for server hello
server: Server is NOT vulnerable with cipher RC4_128_WITH_MD5, Message: 3b: no tls

server: Case 3b; Connection reset by peer when waiting for server hello
server: Server is NOT vulnerable with cipher DES_64_CBC_WITH_MD5, Message: 3b: no tls

Is this running correctly, or is the TLSHandshake actually an issue and I should ignoring these results?

**Comment by djengineerllc** [comment]
I also tried pip install method, but still got the same results on Kali 2

**Comment by Catopuss** [comment]
Having Import Errors also from Kali 2. Getting the below error. 

Traceback (most recent call last):
  File "scanner.py", line 18, in <module>
    from scapy_ssl_tls.ssl_tls import *
ImportError: No module named scapy_ssl_tls.ssl_tls

**Comment by djengineerllc** [comment]
Apparently my import error isn't actually an issue and means that it worked.  
Reference: https://github.com/nimia/public_drown_scanner/issues/5#issuecomment-190818677

**Comment by djengineerllc** [comment]
Looks like your issue is this one though: https://github.com/nimia/public_drown_scanner/issues/12
